### ISSUE TITLE
Nice Program

### ISSUE THREAD

**Issue by GameTec-live** [notchen502/boatgame.io-trading-calc#1]
Hi! I know, that issues are the wrong way to make contac with a person, but i hjave interest, in colaberating with you. and you forgot the .html file extension on the upload. mfg GameTec_live //werner-web
benedikt.werner08@gmail.com
GameTec_live#2350
PS: Please Mail me or contact me over discord!

**Comment by GameTec-live** [comment]
By the way! for only html, it is a nice programm

**Comment by notchen502** [comment]
Sorry for responding this late, considering the fact that I am a beginner in java programing and that I don't know how to use html (even tho I want to learn it), I can't do an html extension file. I will still look into it and add one, if you want to help me contact me through discord: notchen502#9558
